# Generated by Django 4.2.16 on 2026-04-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '000X_create_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='points',
        ),
    ]
