# Generated by Django 4.2 on 2026-01-20 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userstats_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
