# Generated by Django 4.2 on 2026-01-17 09:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Shop Category',
                'verbose_name_plural': 'Shop Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('item_type', models.CharField(choices=[('avatar', 'Avatar'), ('background', 'Backgrounds'), ('frame', 'Cool frames'), ('badge', 'Badges'), ('theme', 'Themes')], max_length=20, verbose_name='Item type')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20, verbose_name='Rarity')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (points)')),
                ('emoji', models.CharField(default='🎁', max_length=10, verbose_name='Emoji')),
                ('color', models.CharField(default='#3498db', max_length=20, verbose_name='Цвет')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.shop_item_image_path, verbose_name='Item image')),
                ('preview_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Цвет превью')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='We recommend')),
                ('unlock_level', models.IntegerField(default=1, verbose_name='Unlock Level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shopcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Shop item',
                'verbose_name_plural': 'Shop items',
                'ordering': ['sort_order', 'price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('equipped', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Invertary',
                'verbose_name_plural': 'User invertary',
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['item_type', 'is_active'], name='shop_shopit_item_ty_f932f3_idx'),
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['category', 'is_active'], name='shop_shopit_categor_df9994_idx'),
        ),
    ]
