# Generated by Django 4.2 on 2026-01-18 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_position_x', models.IntegerField(default=0)),
                ('custom_position_y', models.IntegerField(default=0)),
                ('custom_scale', models.FloatField(default=1.0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avatar Equipment',
                'verbose_name_plural': 'Avatar Equipment',
            },
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_tone', models.CharField(default='#ffdbac', max_length=20)),
                ('body_type', models.CharField(default='average', max_length=20)),
                ('face_type', models.CharField(blank=True, default='neutral', max_length=20)),
                ('background_color', models.CharField(default='#ecf0f1', max_length=20)),
                ('show_shadow', models.BooleanField(default=True)),
                ('avatar_size', models.IntegerField(default=300, help_text='Size in pixels')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Avatar',
                'verbose_name_plural': 'User Avatars',
            },
        ),
        migrations.AlterModelOptions(
            name='shopitem',
            options={'ordering': ['layer', 'sort_order', 'price', 'name'], 'verbose_name': 'Shop item', 'verbose_name_plural': 'Shop items'},
        ),
        migrations.AlterModelOptions(
            name='userinventory',
            options={'ordering': ['-equipped', '-purchased_at'], 'verbose_name': 'User Inventory', 'verbose_name_plural': 'User Inventory'},
        ),
        migrations.RemoveIndex(
            model_name='shopitem',
            name='shop_shopit_categor_df9994_idx',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='color',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='charisma_bonus',
            field=models.IntegerField(default=0, help_text='Community influence'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='compatible_with',
            field=models.ManyToManyField(blank=True, help_text='Items this can be combined with', related_name='compatible_items', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='exclusive_with',
            field=models.ManyToManyField(blank=True, help_text='Items this cannot be combined with', related_name='exclusive_items', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='gender',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='health_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='height',
            field=models.IntegerField(default=100, help_text='Image height in pixels'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='layer',
            field=models.IntegerField(choices=[(0, 'Background'), (1, 'Body/Skin'), (2, 'Pants/Shoes'), (3, 'Shirt'), (4, 'Facial Hair'), (5, 'Hair'), (6, 'Glasses'), (7, 'Hat'), (8, 'Accessories'), (9, 'Face'), (10, 'Frame'), (11, 'Badge')], default=3, help_text='Render layer'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='mood_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='position_x',
            field=models.IntegerField(default=0, help_text='Horizontal offset from center'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='position_y',
            field=models.IntegerField(default=0, help_text='Vertical offset from center'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='primary_color',
            field=models.CharField(default='#3498db', max_length=20, verbose_name='Primary color'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='scale',
            field=models.FloatField(default=1.0, help_text='Scale multiplier (0.5-2.0)'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='secondary_color',
            field=models.CharField(blank=True, default='#2980b9', max_length=20, verbose_name='Secondary color'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='width',
            field=models.IntegerField(default=100, help_text='Image width in pixels'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='xp_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='custom_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='wear_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('skin', 'Skin Tone'), ('body', 'Body Type'), ('face', 'Face'), ('hair', 'Hair'), ('hair_color', 'Hair Color'), ('shirt', 'Shirt/Top'), ('pants', 'Pants/Bottom'), ('shoes', 'Shoes'), ('glasses', 'Glasses'), ('hat', 'Hat'), ('accessory', 'Accessory'), ('facial_hair', 'Facial Hair'), ('avatar', 'Avatar'), ('background', 'Backgrounds'), ('frame', 'Cool frames'), ('badge', 'Badges'), ('theme', 'Themes')], max_length=20, verbose_name='Item type'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='preview_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Preview color'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20, verbose_name='Rarity'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort order'),
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['layer', 'gender'], name='shop_shopit_layer_f26e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['category', 'rarity'], name='shop_shopit_categor_60725e_idx'),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='equipped_items',
            field=models.ManyToManyField(related_name='avatar_equipments', through='shop.AvatarEquipment', to='shop.userinventory'),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avatarequipment',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.useravatar'),
        ),
        migrations.AddField(
            model_name='avatarequipment',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.userinventory'),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='avatar_equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item_ref', to='shop.avatarequipment'),
        ),
        migrations.AlterUniqueTogether(
            name='avatarequipment',
            unique_together={('avatar', 'inventory_item')},
        ),
    ]
