# Generated by Django 4.2.16 on 2026-04-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_avatarequipment_useravatar_alter_shopitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Use this instead of uploading file', max_length=500, null=True, verbose_name='External image URL (Google Drive, etc.)'),
        ),
    ]
