# Generated by Django 4.2 on 2026-01-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='dailytask',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='age_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='age_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
