# Generated by Django 5.2.8 on 2026-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_category_options_dailytask_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='max_attempts',
            field=models.IntegerField(default=3, help_text='Maximum attempts allowed'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='passing_score',
            field=models.IntegerField(default=70, help_text='Passing score in %'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='theory_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs'),
        ),
    ]
