# Generated by Django 4.2.16 on 2026-04-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_lesson_max_attempts_lesson_passing_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytask',
            old_name='points',
            new_name='coins',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='points',
            new_name='coins',
        ),
        migrations.RenameField(
            model_name='lessonprogress',
            old_name='points_earned',
            new_name='coins_earned',
        ),
    ]
